### PR TITLE
Update builder to use Puppet 6

### PR DESCRIPTION
**Pull request by tprestegard**
I've built this image and used it to build Tortuga, and then installed the new Tortuga build successfully. I also removed the use of non-standard `pip`.

### CODE REVIEW

**Review by dtougas — COMMENTED** [review]
My understanding of how Docker works is that each RUN command will create a new filesystem layer, hence the reason we ran all the commands in a single RUN command.

**Comment by tprestegard** [comment]
> My understanding of how Docker works is that each RUN command will create a new filesystem layer, hence the reason we ran all the commands in a single RUN command.

I think that's true.  Is there a benefit beyond just shrinking the image size?  I tested a change to the new `Dockerfile` to combine all of the `rpm` and `yum` commands into one `RUN` statement and it saves a little space (resulting image is 1.3 GB instead of 1.54 GB).

So I guess the question is one of Dockerfile readability vs. image size.  Do you have a strong preference? I think I lean towards readability since a 20% bump in image size shouldn't matter much for this application.

**Comment by dtougas** [comment]
I will defer to @cameronbrunner on this, as he was the one who originally told me to rewrite this as a single `RUN` command when I worked on this in the past.

**Comment by cameronbrunner** [comment]
Only feedback... it doesn't make sense to clear the cache in a separate RUN commands as all it does is mask files from a previous layer (it actually takes more space in the image to hide the files from the previous layers).  So remove that RUN or add it to each of your yum calls.  These changes would get back most of the extra space the multiple RUN statements added.

**Comment by cameronbrunner** [comment]
LGTM!

**Pull request merged**
